### ISSUE TITLE
12. Integer to Roman 

### ISSUE THREAD

**Issue by MadhuSaini22** [tanyagupta0201/LeetCode-Problems-Solutions#120]
@tanyagupta0201 , Please assign this task to me with Hacktoberfest2022 label.
#Collboration 1st, Code 2nd

**Comment by tanyagupta0201** [comment]
Which Language ?

**Comment by MadhuSaini22** [comment]
> 

JAVA

**Comment by MadhuSaini22** [comment]
@tanyagupta0201 , If we don't have Hacktoberfest accepted labels on merged PRs then that won't be included in Hacktoberfest2022 so please put labels?
And one more question, does this repo is part of Hacktoberfest2022 or not?
