### ISSUE TITLE
58. Length of Last Word

### ISSUE THREAD

**Issue by tusharjayanti** [tanyagupta0201/LeetCode-Problems-Solutions#154]
https://leetcode.com/problems/length-of-last-word/
Kindly assign this to me

**Comment by tusharjayanti** [comment]
@tanyagupta0201 kindly assign this to me

**Comment by tanyagupta0201** [comment]
stale issue

**Comment by tusharjayanti** [comment]
I would like to contribute. 
Could you please re-open this? 
@tanyagupta0201
