### ISSUE TITLE
11. Container With Most Water

### ISSUE THREAD

**Issue by tusharjayanti** [tanyagupta0201/LeetCode-Problems-Solutions#155]
https://leetcode.com/problems/container-with-most-water/
Please assign this to me.

**Comment by tusharjayanti** [comment]
@tanyagupta0201 kindly assign this to me

**Comment by tanyagupta0201** [comment]
stale issue

**Comment by tusharjayanti** [comment]
I want to contribute. 
Could you please reopen this issue?
@tanyagupta0201
