### ISSUE TITLE
1578_Minimum Time to Make Rope Colorful

### ISSUE THREAD

**Issue by piyush0411** [tanyagupta0201/LeetCode-Problems-Solutions#161]
Please assign this issue to me.
[1578_Minimum Time to Make Rope Colorful](https://leetcode.com/problems/minimum-time-to-make-rope-colorful/)

**Comment by tanyagupta0201** [comment]
Which language ?

**Comment by piyush0411** [comment]
Language - C++

**Comment by tanyagupta0201** [comment]
This has been done in C++
