### ISSUE TITLE
Organizing the solutions

### ISSUE THREAD

**Issue by adityachache** [tanyagupta0201/LeetCode-Problems-Solutions#171]
Won't it be better if the solutions were organized according to their difficulty level? in different subfolders?
like easy, medium and hard subfolders for all the problems

**Comment by tanyagupta0201** [comment]
No, I have made folders according to the languages. If I would make folders according to the difficulty level there would 9 folders in total and it may create confusion among the contributors. Also, it would become difficult to manage it.
