### ISSUE TITLE
42. Trapping Rain Water in java

### ISSUE THREAD

**Issue by MadhuSaini22** [tanyagupta0201/LeetCode-Problems-Solutions#194]
@tanyagupta0201 , please assign this task to me

**Comment by abhayanand08** [comment]
@tanyagupta0201 I would like to add an efficient approach to this issue. Kindly assign this issue to me.

**Comment by tanyagupta0201** [comment]
> @tanyagupta0201 I would like to add an efficient approach to this issue. Kindly assign this issue to me.

You may do it in a language other than java.

**Comment by shivesh41kr** [comment]
@tanyagupta0201 please have a look on Trapping Rain Water in C++ https://github.com/tanyagupta0201/LeetCode-Problems-Solutions/pull/277  code with full explanation and also with time and space complexity.
