### ISSUE TITLE
Python solutions for 4sum_ii, Majority Element, Group Anagrams

### ISSUE THREAD

**Issue by dkarakay** [tanyagupta0201/LeetCode-Problems-Solutions#203]
Python solutions for 

4sum_ii (https://leetcode.com/problems/4sum-ii/)
Majority Element (https://leetcode.com/problems/majority-element/)
Group Anagrams (https://leetcode.com/problems/group-anagrams/)

**Comment by nitishgiri007** [comment]
hi @dkarakay  want this repo for my contribution please help me by providing this
