### ISSUE TITLE
Python solution for 838_PushDominoes

### ISSUE THREAD

**Issue by Himanshigarg08** [tanyagupta0201/LeetCode-Problems-Solutions#216]

**Comment by codedoc7** [comment]
find the solution of the Push Dominoes problem

class Solution(object):
    def pushDominoes(self, d):
        """
        :type dominoes: str
        :rtype: str
        """
        d = "L" + d + "R"
        res = []
        l = 0
        for r in range(1, len(d)):
            if d[r] == '.':
                continue
            mid = r - l - 1
            if l:
                res.append(d[l])
            if d[l] == d[r]:
                res.append(d[l] * mid)
            elif d[l] == 'L' and d[r] == 'R':
                res.append('.' * mid)
            else:
                res.append('R' * (mid // 2) + '.' * (mid % 2) + 'L' * (mid // 2))
            l = r
        return "".join(res)
