### ISSUE TITLE
50. Pow(x, n) in C++

### ISSUE THREAD

**Issue by chandansahuji** [tanyagupta0201/LeetCode-Problems-Solutions#229]
Implement [pow(x, n)](http://www.cplusplus.com/reference/valarray/pow/), which calculates x raised to the power n (i.e., x^n).

**Comment by Himanshigarg08** [comment]
@tanyagupta0201 Assign this issue to me!!

**Comment by tanyagupta0201** [comment]
> @tanyagupta0201 Assign this issue to me!!

you may contribute in other language
