### ISSUE TITLE
1881. Maximum Value after Insertion

### ISSUE THREAD

**Issue by RohanKGP** [tanyagupta0201/LeetCode-Problems-Solutions#28]
@tanyagupta0201 Can you please assign me this task.
Link : https://leetcode.com/problems/maximum-value-after-insertion/

**Comment by RohanKGP** [comment]
@tanyagupta0201 Task Completed. Please look into the Pull Request and add the hacktoberfest-accepted label.

**Comment by tanyagupta0201** [comment]
merged
