### ISSUE TITLE
300. Longest Increasing Subsequence C++

### ISSUE THREAD

**Issue by singhsv13** [tanyagupta0201/LeetCode-Problems-Solutions#287]
https://leetcode.com/problems/longest-increasing-subsequence/ 
assign me this problem

**Comment by tanyagupta0201** [comment]
I hope now you are sure for opening this issue 😂. Therefore, assigning this issue to you.

**Comment by tanyagupta0201** [comment]
> I was trying something but it failed 😅

No problem
