### ISSUE TITLE
27. Remove Element (Python)

### ISSUE THREAD

**Issue by avi78** [tanyagupta0201/LeetCode-Problems-Solutions#374]
I want to add python problem. Can you assign me the work. Thank You

**Comment by tanyagupta0201** [comment]
Write leetcode problem name

**Comment by avi78** [comment]
27. Remove Element

**Comment by tanyagupta0201** [comment]
> 27. Remove Element

Assigned.
Next time keep your issue name like I have changed now.

**Comment by tanyagupta0201** [comment]
merged
