### ISSUE TITLE
#32 Longest Valid Parentheses

### ISSUE THREAD

**Issue by nihar2907** [tanyagupta0201/LeetCode-Problems-Solutions#375]
Given a string containing just the characters '(' and ')', find the length of the longest valid (well-formed) parentheses substring.

Example 1:

Input: s = "(()"
Output: 2
Explanation: The longest valid parentheses substring is "()".

Example 2:
Input: s = ")()())"
Output: 4
Explanation: The longest valid parentheses substring is "()()".

**Comment by soniya2008** [comment]
!assign
