### ISSUE TITLE
121. Best Time to Buy and Sell Stock

### ISSUE THREAD

**Issue by adarshgupta404** [tanyagupta0201/LeetCode-Problems-Solutions#42]
Please assign me this
https://leetcode.com/problems/best-time-to-buy-and-sell-stock/

**Comment by devrudra9** [comment]
Hey @tanyagupta0201 please assign me this problem !!

**Comment by gargshruti** [comment]
Please assign this issue to me.

**Comment by adarshgupta404** [comment]
@tanyagupta0201 leaving this question you can assign it to anyone of them.

**Comment by satendragangwar** [comment]
please assign this issue to me
