### ISSUE TITLE
#152. Maximum Product Subarray

### ISSUE THREAD

**Issue by stuti-v4** [tanyagupta0201/LeetCode-Problems-Solutions#427]
Given an integer array, find a contiguous non-empty subarray within the array that has the largest product, and return the product.

**Comment by RiyaArora02** [comment]
Hii sir can you assign this issue to me I would like to contribute in it

**Comment by tanyagupta0201** [comment]
> Hii sir can you assign this issue to me I would like to contribute in it

fcfs
