### ISSUE TITLE
guessing the number in java

### ISSUE THREAD

**Issue by utkarshaskumbhar** [tanyagupta0201/LeetCode-Problems-Solutions#575]
assign me this issue

**Comment by tanyagupta0201** [comment]
Paste the leetcode link of this problem in comments.

**Comment by utkarshaskumbhar** [comment]
https://leetcode.com/problems/guess-number-higher-or-lower/description/

**Comment by utkarshaskumbhar** [comment]
Here is the link now can you assign me
