### ISSUE TITLE
103. Binary Tree Zigzag Level Order Traversal

### ISSUE THREAD

**Issue by karthiksenthil2803** [tanyagupta0201/LeetCode-Problems-Solutions#63]
Please Assign me this task !!.
https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/

**Comment by tanyagupta0201** [comment]
Problem already assigned in #9

**Comment by karthiksenthil2803** [comment]
I am sorry for not noticing this earlier... Should I close this issue ?

**Comment by tanyagupta0201** [comment]
Do you want to solve this problem in Java or Python?

**Comment by karthiksenthil2803** [comment]
No I am sorry I am not familiar for competitive programming apart from c++.
Thank you mam

**Comment by tanyagupta0201** [comment]
okay, close the issue then.
