### ISSUE TITLE
61. Rotate List

### ISSUE THREAD

**Issue by adarshgupta404** [tanyagupta0201/LeetCode-Problems-Solutions#73]
Please Assign me this.
https://leetcode.com/problems/rotate-list/

**Comment by adarshgupta404** [comment]
please also review my #45 issue's code and if everything is ok then merge.

**Comment by adarshgupta404** [comment]
Is there any issue?

**Comment by tanyagupta0201** [comment]
> Is there any issue?

Sir I have already merged your code. So, I closed this issue as it was completed.

**Comment by adarshgupta404** [comment]
thank you
