### ISSUE TITLE
21. Merge two sorted lists in C++

### ISSUE THREAD

**Issue by Farhan-2222** [tanyagupta0201/LeetCode-Problems-Solutions#84]

**Comment by rnavaneeth992** [comment]
@Farhan-2222 Can you assign me this task

**Comment by Farhan-2222** [comment]
> @Farhan-2222 Can you assign me this task

I have already completed and sent the pull request

**Comment by tanyagupta0201** [comment]
> > @Farhan-2222 Can you assign me this task
> 
> I have already completed and sent the pull request

Did I assign this issue to you ?
Then why did you create Pull request ?

**Comment by Farhan-2222** [comment]
> > > @Farhan-2222 Can you assign me this task
> > 
> > I have already completed and sent the pull request
> 
> Did I assign this issue to you ?
> Then why did you create Pull request ?

I searched for it but couldn't find the code for it. That's why I commited this code as a pull request.

But anyway can you tell me if this repository is included in hacktoberfest or not?

**Comment by tanyagupta0201** [comment]
> > > > @Farhan-2222 Can you assign me this task
> > > 
> > > 
> > > I have already completed and sent the pull request
> > 
> > 
> > Did I assign this issue to you ?
> > Then why did you create Pull request ?
> 
> I searched for it but couldn't find the code for it. That's why I commited this code as a pull request.
> 
> But anyway can you tell me if this repository is included in hacktoberfest or not?

This repo is taking part in Hacktoberfest. 
This time I am merging your PR but next time please make sure to create a PR only after an issue is assigned to you.
It becomes difficult for the maintainer to keep track of all the files.

**Comment by tanyagupta0201** [comment]
@rnavaneeth992 this problem has been merged in C++. Do you want to do this problem in Python or Java ?

**Comment by Farhan-2222** [comment]
Ok mam thanks you. I will try to do few more questions.

**Comment by himanshuj0007** [comment]
hi please assign me this issues

**Comment by tanyagupta0201** [comment]
> hi please assign me this issues

In which Language ?

**Comment by rnavaneeth992** [comment]
> @rnavaneeth992 this problem has been merged in C++. Do you want to do this problem in Python or Java ?

Python
I can do

**Comment by himanshuj0007** [comment]
c/c++

**Comment by rnavaneeth992** [comment]
> > @rnavaneeth992 this problem has been merged in C++. Do you want to do this problem in Python or Java ?
> 
> Python I can do

@tanyagupta0201
